unit TestMREWSynch;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, sysutils, windows, uEvsSyncObjs;

type
  // Test methods for class TEvsSemaSynchronizer
  
  TTestEvsMREWSynchronizer = class(TTestCase)
  strict private
    FEvsSemaSynchronizer: TEvsSemaSynchronizer;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestStartRead;
    procedure TestStartWrite;
    procedure TestEndRead;
    procedure TestEndWrite;
  end;

implementation

procedure TTestEvsMREWSynchronizer.SetUp;
begin
  FEvsSemaSynchronizer := TEvsSemaSynchronizer.Create;
end;

procedure TTestEvsMREWSynchronizer.TearDown;
begin
  FEvsSemaSynchronizer.Free;
  FEvsSemaSynchronizer := nil;
end;

procedure TTestEvsMREWSynchronizer.TestStartRead;
begin
  FEvsSemaSynchronizer.StartRead;
  // TODO: Validate method results
end;

procedure TTestEvsMREWSynchronizer.TestStartWrite;
begin
  FEvsSemaSynchronizer.StartWrite;
  // TODO: Validate method results
end;

procedure TTestEvsMREWSynchronizer.TestEndRead;
begin
  FEvsSemaSynchronizer.EndRead;
  // TODO: Validate method results
end;

procedure TTestEvsMREWSynchronizer.TestEndWrite;
begin
  FEvsSemaSynchronizer.EndWrite;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TTestEvsMREWSynchronizer.Suite);
end.

