unit TestEvsMutex;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, sysutils, windows, uEvsSyncObjs;

type
  // Test methods for class TEvsMutex
  
  TestTEvsMutex = class(TTestCase)
  strict private
    FEvsMutex: TEvsMutex;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestAcquire;
    procedure TestRelease;
    procedure TestTryAcquire;
    procedure TestEnter;
    procedure TestLeave;
  end;

implementation

procedure TestTEvsMutex.SetUp;
begin
  FEvsMutex := TEvsMutex.Create;
end;

procedure TestTEvsMutex.TearDown;
begin
  FEvsMutex.Free;
  FEvsMutex := nil;
end;

procedure TestTEvsMutex.TestAcquire;
begin
  FEvsMutex.Acquire;
  // TODO: Validate method results
end;

procedure TestTEvsMutex.TestRelease;
begin
  FEvsMutex.Release;
  // TODO: Validate method results
end;

procedure TestTEvsMutex.TestTryAcquire;
var
  ReturnValue: Boolean;
begin
  // TODO: Setup method call parameters
  ReturnValue := FEvsMutex.TryAcquire(10);
  // TODO: Validate method results
end;

procedure TestTEvsMutex.TestEnter;
begin
  FEvsMutex.Enter;
  // TODO: Validate method results
end;

procedure TestTEvsMutex.TestLeave;
begin
  FEvsMutex.Leave;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTEvsMutex.Suite);
end.

